language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

matrix:

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - (cd examples/laravel-5 && cp ../../composer.phar . && php composer.phar install)

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - vendor/bin/phpunit
  - (cd examples/laravel-5 && vendor/bin/phpunit)
