language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - cd examples/laravel-4 && curl -s http://getcomposer.org/installer | php && php composer.phar install

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - phpunit
  - cd examples/laravel-4 && phpunit
